apiVersion: v2
name: my-app
description: A Helm chart for my application
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: postgresql
    version: "18.1.13"
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: "24.0.0"
    repository: https://charts.bitnami.com/bitnami